### ISSUE TITLE
Do you have any processed data for training?

### ISSUE THREAD

**Issue by Alicebash** [XuyangBai/PointDSC#2]
Hello,I'm trying to reproduce this code, but I'm having some problems.
-----------------------------------------------------------------------------------------------------------------------------
I have the catalogue ready:
.                          
├── fragments                 
│   ├── 7-scene-redkitechen/       
│   ├── sun3d-home_at-home_at_scan1_2013_jan_1/      
│   └── ...                
├── gt_result                   
│   ├── 7-scene-redkitechen-evaluation/   
│   ├── sun3d-home_at-home_at_scan1_2013_jan_1-evaluation/
│   └── ...         
├── threedmatch            
│   ├── *.npz
│   └── *.txt       
----------------------------------------------------------------------------------------------------------------------
But Error when I run training code"python train_3DMatch.py":
"AssertionError: Make sure that the path /data/3DMatch has data sun3d-brown_bm_1-brown_bm_1*0.30.txt"
Did I do something wrong?
And my files failed to install"MinkowskiEngine".
Could you please provide this folder "/3DMatch" used for training ?
Thank you!

**Comment by XuyangBai** [comment]
> "AssertionError: Make sure that the path /data/3DMatch has data sun3d-brown_bm_1-brown_bm_1*0.30.txt"
> Did I do something wrong?

You need to make sure your npz and txt files are  in  `/data/3DMatch/threedmatch`  folder as we load the npz file by
https://github.com/XuyangBai/PointDSC/blob/b009d536ac10b570853833f2178397c154745da9/datasets/ThreeDMatch.py#L48-L50

And I am not able to share the extracted FCGF feature with you because the files are too large. You can follow the instruction of https://github.com/NVIDIA/MinkowskiEngine to install the ME or try to use FPFH feature first. Extracting FPFH feature does not need ME, you can do it using `misc/cal_fpfh.py`

**Comment by XuyangBai** [comment]
please reopen if you have more questions.

**Comment by hagianga21** [comment]
Indeed, the error still remains. The reason is that you try to import the filenames "sun3d-brown_bm_1-brown_bm_1*0.30.txt". However, in the data folder, the filenames are something likes "sun3d-brown_bm_1-brown_bm_1@seq-01-0.30.txt".

Could you help me fix the errors? As there are a lot of seqs in some files. For example, in 7-scenes-chess we have seq-01 to seq-06. Do you use all of seqs during training?
